### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by tim-oleksii** [ken-yossy/nvme-model-for-qemu#1]
Hello @ken-yossy ,

I've browsed this thing, it looks awesome - just pure drive emulation with all possible driver quirks analysis.

What it needs even more - some kind of build/integration instructions. With Win10 20H2 coming, I guess I can use it to analyze storNVMe behaviour. Even more - proper compliance tests might be created that can automatically generate report.

Thanks!
Alexey

**Comment by ken-yossy** [comment]
Hello Alexey,

Thank you for your suggestion. You made the very first comment for this repository!

But I think I do not have enough time to make contribution to this repository frequently...

> What it needs even more - some kind of build/integration instructions. With Win10 20H2 coming, I guess I can use it to analyze storNVMe behaviour. Even more - proper compliance tests might be created that can automatically generate report.

As you said, the NVMe drive emulation in Qemu is very pure and simple one, so it is suitable for testing and analyzing OS's behavior.

If you need an NVMe drive emulation that is easy to customize or have plans to do creative works with it, I strongly recommend using Qemu's official source tree in git repository[1]. It supports Asynchronous Event Request command and Persistent Memory Region (PMR)!! 

[1] You can find it in https://www.qemu.org/download/#source

Kind regards,
Ken
